scout_mini:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30 

  #Velocity  Controllers ---------------------------------------
  front_right_wheel_controller:
    type: velocity_controllers/JointVelocityController 
    joint: front_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  front_left_wheel_controller:
    type: velocity_controllers/JointVelocityController 
    joint: front_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  rear_left_wheel_controller:
    type: velocity_controllers/JointVelocityController 
    joint: rear_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  rear_right_wheel_controller:
    type: velocity_controllers/JointVelocityController 
    joint: rear_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}