obstacle_range: 7.5
raytrace_range: 8.0
footprint: [[-0.2319755, -0.2082515], [-0.2319755, 0.2082515], [0.2319755, 0.2082515], [0.2319755, -0.2082515]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_link , data_type: LaserScan, topic: scan, marking: true, clearing: true}